name: Flat
on:
  schedule:
    - cron: '*/30 16-19 * * *'
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://api.coronavirus.data.gov.uk/v2/data?areaType=region&metric=newCasesByPublishDate&metric=newCasesBySpecimenDate&metric=cumCasesByPublishDate&format=csv
          downloaded_filename: raw.csv
          postprocess: ./postprocess.ts # Script to run upon download completion

